# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_plotGui(object):
    def setupUi(self, plotGui):
        plotGui.setObjectName("plotGui")
        plotGui.resize(831, 471)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(plotGui.sizePolicy().hasHeightForWidth())
        plotGui.setSizePolicy(sizePolicy)
        self.fileProp = QtWidgets.QGroupBox(plotGui)
        self.fileProp.setGeometry(QtCore.QRect(10, 10, 381, 231))
        self.fileProp.setObjectName("fileProp")
        self.listDir = QtWidgets.QListWidget(self.fileProp)
        self.listDir.setGeometry(QtCore.QRect(10, 50, 361, 141))
        self.listDir.setObjectName("listDir")
        self.currentDir = QtWidgets.QLineEdit(self.fileProp)
        self.currentDir.setGeometry(QtCore.QRect(10, 20, 251, 21))
        self.currentDir.setObjectName("currentDir")
        self.browseBtn = QtWidgets.QPushButton(self.fileProp)
        self.browseBtn.setGeometry(QtCore.QRect(270, 20, 101, 23))
        self.browseBtn.setAutoDefault(False)
        self.browseBtn.setObjectName("browseBtn")
        self.loadStatus = QtWidgets.QLabel(self.fileProp)
        self.loadStatus.setGeometry(QtCore.QRect(10, 200, 361, 21))
        self.loadStatus.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.loadStatus.setObjectName("loadStatus")
        self.horizontalLayoutWidget = QtWidgets.QWidget(plotGui)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 250, 811, 211))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.batteryConfigLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.batteryConfigLayout.setContentsMargins(0, 0, 0, 0)
        self.batteryConfigLayout.setObjectName("batteryConfigLayout")
        self.battery1 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.battery1.setObjectName("battery1")
        self.Peukert1 = QtWidgets.QGroupBox(self.battery1)
        self.Peukert1.setGeometry(QtCore.QRect(10, 20, 231, 71))
        self.Peukert1.setTitle("")
        self.Peukert1.setObjectName("Peukert1")
        self.slidePeu1 = QtWidgets.QSlider(self.Peukert1)
        self.slidePeu1.setGeometry(QtCore.QRect(10, 40, 211, 22))
        self.slidePeu1.setMinimum(75)
        self.slidePeu1.setMaximum(200)
        self.slidePeu1.setProperty("value", 110)
        self.slidePeu1.setOrientation(QtCore.Qt.Horizontal)
        self.slidePeu1.setObjectName("slidePeu1")
        self.inputPeu1 = QtWidgets.QSpinBox(self.Peukert1)
        self.inputPeu1.setGeometry(QtCore.QRect(130, 10, 91, 21))
        self.inputPeu1.setProperty("showGroupSeparator", True)
        self.inputPeu1.setPrefix("")
        self.inputPeu1.setMinimum(75)
        self.inputPeu1.setMaximum(200)
        self.inputPeu1.setProperty("value", 110)
        self.inputPeu1.setDisplayIntegerBase(10)
        self.inputPeu1.setObjectName("inputPeu1")
        self.peuLbl1 = QtWidgets.QLabel(self.Peukert1)
        self.peuLbl1.setGeometry(QtCore.QRect(10, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.peuLbl1.setFont(font)
        self.peuLbl1.setScaledContents(True)
        self.peuLbl1.setObjectName("peuLbl1")
        self.Efficiency1 = QtWidgets.QGroupBox(self.battery1)
        self.Efficiency1.setGeometry(QtCore.QRect(10, 90, 231, 71))
        self.Efficiency1.setTitle("")
        self.Efficiency1.setObjectName("Efficiency1")
        self.slideEff1 = QtWidgets.QSlider(self.Efficiency1)
        self.slideEff1.setGeometry(QtCore.QRect(10, 40, 211, 22))
        self.slideEff1.setMinimum(0)
        self.slideEff1.setMaximum(150)
        self.slideEff1.setProperty("value", 50)
        self.slideEff1.setOrientation(QtCore.Qt.Horizontal)
        self.slideEff1.setObjectName("slideEff1")
        self.inputEff1 = QtWidgets.QSpinBox(self.Efficiency1)
        self.inputEff1.setGeometry(QtCore.QRect(130, 10, 91, 22))
        self.inputEff1.setMaximum(150)
        self.inputEff1.setProperty("value", 50)
        self.inputEff1.setObjectName("inputEff1")
        self.effLbl1 = QtWidgets.QLabel(self.Efficiency1)
        self.effLbl1.setGeometry(QtCore.QRect(10, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.effLbl1.setFont(font)
        self.effLbl1.setScaledContents(True)
        self.effLbl1.setObjectName("effLbl1")
        self.Capacity1 = QtWidgets.QGroupBox(self.battery1)
        self.Capacity1.setGeometry(QtCore.QRect(10, 160, 231, 41))
        self.Capacity1.setTitle("")
        self.Capacity1.setObjectName("Capacity1")
        self.capLbl1 = QtWidgets.QLabel(self.Capacity1)
        self.capLbl1.setGeometry(QtCore.QRect(10, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.capLbl1.setFont(font)
        self.capLbl1.setObjectName("capLbl1")
        self.inputCap1 = QtWidgets.QSpinBox(self.Capacity1)
        self.inputCap1.setGeometry(QtCore.QRect(130, 10, 91, 22))
        self.inputCap1.setObjectName("inputCap1")
        self.batteryConfigLayout.addWidget(self.battery1)
        self.battery2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.battery2.setObjectName("battery2")
        self.Capacity2 = QtWidgets.QGroupBox(self.battery2)
        self.Capacity2.setGeometry(QtCore.QRect(10, 160, 231, 41))
        self.Capacity2.setTitle("")
        self.Capacity2.setObjectName("Capacity2")
        self.capLbl2 = QtWidgets.QLabel(self.Capacity2)
        self.capLbl2.setGeometry(QtCore.QRect(10, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.capLbl2.setFont(font)
        self.capLbl2.setObjectName("capLbl2")
        self.inputCap2 = QtWidgets.QSpinBox(self.Capacity2)
        self.inputCap2.setGeometry(QtCore.QRect(130, 10, 91, 22))
        self.inputCap2.setObjectName("inputCap2")
        self.Efficiency2 = QtWidgets.QGroupBox(self.battery2)
        self.Efficiency2.setGeometry(QtCore.QRect(10, 90, 231, 71))
        self.Efficiency2.setTitle("")
        self.Efficiency2.setObjectName("Efficiency2")
        self.slideEff2 = QtWidgets.QSlider(self.Efficiency2)
        self.slideEff2.setGeometry(QtCore.QRect(10, 40, 211, 22))
        self.slideEff2.setMinimum(0)
        self.slideEff2.setMaximum(150)
        self.slideEff2.setProperty("value", 50)
        self.slideEff2.setOrientation(QtCore.Qt.Horizontal)
        self.slideEff2.setObjectName("slideEff2")
        self.inputEff2 = QtWidgets.QSpinBox(self.Efficiency2)
        self.inputEff2.setGeometry(QtCore.QRect(130, 10, 91, 22))
        self.inputEff2.setMinimum(0)
        self.inputEff2.setMaximum(150)
        self.inputEff2.setProperty("value", 50)
        self.inputEff2.setObjectName("inputEff2")
        self.effLbl2 = QtWidgets.QLabel(self.Efficiency2)
        self.effLbl2.setGeometry(QtCore.QRect(10, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.effLbl2.setFont(font)
        self.effLbl2.setScaledContents(True)
        self.effLbl2.setObjectName("effLbl2")
        self.Peukert2 = QtWidgets.QGroupBox(self.battery2)
        self.Peukert2.setGeometry(QtCore.QRect(10, 20, 231, 71))
        self.Peukert2.setTitle("")
        self.Peukert2.setObjectName("Peukert2")
        self.slidePeu2 = QtWidgets.QSlider(self.Peukert2)
        self.slidePeu2.setGeometry(QtCore.QRect(10, 40, 211, 22))
        self.slidePeu2.setMinimum(75)
        self.slidePeu2.setMaximum(200)
        self.slidePeu2.setProperty("value", 110)
        self.slidePeu2.setOrientation(QtCore.Qt.Horizontal)
        self.slidePeu2.setObjectName("slidePeu2")
        self.inputPeu2 = QtWidgets.QSpinBox(self.Peukert2)
        self.inputPeu2.setGeometry(QtCore.QRect(130, 10, 91, 22))
        self.inputPeu2.setMinimum(75)
        self.inputPeu2.setMaximum(200)
        self.inputPeu2.setProperty("value", 110)
        self.inputPeu2.setObjectName("inputPeu2")
        self.peuLbl2 = QtWidgets.QLabel(self.Peukert2)
        self.peuLbl2.setGeometry(QtCore.QRect(10, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.peuLbl2.setFont(font)
        self.peuLbl2.setScaledContents(True)
        self.peuLbl2.setObjectName("peuLbl2")
        self.batteryConfigLayout.addWidget(self.battery2)
        self.battery3 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.battery3.setObjectName("battery3")
        self.Capacity3 = QtWidgets.QGroupBox(self.battery3)
        self.Capacity3.setGeometry(QtCore.QRect(10, 160, 231, 41))
        self.Capacity3.setTitle("")
        self.Capacity3.setObjectName("Capacity3")
        self.capLbl3 = QtWidgets.QLabel(self.Capacity3)
        self.capLbl3.setGeometry(QtCore.QRect(10, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.capLbl3.setFont(font)
        self.capLbl3.setObjectName("capLbl3")
        self.inputCap3 = QtWidgets.QSpinBox(self.Capacity3)
        self.inputCap3.setGeometry(QtCore.QRect(130, 10, 91, 22))
        self.inputCap3.setObjectName("inputCap3")
        self.Efficiency3 = QtWidgets.QGroupBox(self.battery3)
        self.Efficiency3.setGeometry(QtCore.QRect(10, 90, 231, 71))
        self.Efficiency3.setTitle("")
        self.Efficiency3.setObjectName("Efficiency3")
        self.slideEff3 = QtWidgets.QSlider(self.Efficiency3)
        self.slideEff3.setGeometry(QtCore.QRect(10, 40, 211, 22))
        self.slideEff3.setMinimum(0)
        self.slideEff3.setMaximum(150)
        self.slideEff3.setProperty("value", 50)
        self.slideEff3.setOrientation(QtCore.Qt.Horizontal)
        self.slideEff3.setObjectName("slideEff3")
        self.inputEff3 = QtWidgets.QSpinBox(self.Efficiency3)
        self.inputEff3.setGeometry(QtCore.QRect(130, 10, 91, 22))
        self.inputEff3.setAccelerated(True)
        self.inputEff3.setMaximum(150)
        self.inputEff3.setProperty("value", 50)
        self.inputEff3.setDisplayIntegerBase(10)
        self.inputEff3.setObjectName("inputEff3")
        self.effLbl3 = QtWidgets.QLabel(self.Efficiency3)
        self.effLbl3.setGeometry(QtCore.QRect(10, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.effLbl3.setFont(font)
        self.effLbl3.setScaledContents(True)
        self.effLbl3.setObjectName("effLbl3")
        self.Peukert3 = QtWidgets.QGroupBox(self.battery3)
        self.Peukert3.setGeometry(QtCore.QRect(10, 20, 231, 71))
        self.Peukert3.setTitle("")
        self.Peukert3.setObjectName("Peukert3")
        self.slidePeu3 = QtWidgets.QSlider(self.Peukert3)
        self.slidePeu3.setGeometry(QtCore.QRect(10, 40, 211, 22))
        self.slidePeu3.setMinimum(75)
        self.slidePeu3.setMaximum(200)
        self.slidePeu3.setProperty("value", 110)
        self.slidePeu3.setOrientation(QtCore.Qt.Horizontal)
        self.slidePeu3.setObjectName("slidePeu3")
        self.inputPeu3 = QtWidgets.QSpinBox(self.Peukert3)
        self.inputPeu3.setGeometry(QtCore.QRect(130, 10, 91, 22))
        self.inputPeu3.setMinimum(75)
        self.inputPeu3.setMaximum(200)
        self.inputPeu3.setProperty("value", 110)
        self.inputPeu3.setObjectName("inputPeu3")
        self.peuLbl3 = QtWidgets.QLabel(self.Peukert3)
        self.peuLbl3.setGeometry(QtCore.QRect(10, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.peuLbl3.setFont(font)
        self.peuLbl3.setScaledContents(True)
        self.peuLbl3.setObjectName("peuLbl3")
        self.batteryConfigLayout.addWidget(self.battery3)
        self.plotButton = QtWidgets.QPushButton(plotGui)
        self.plotButton.setGeometry(QtCore.QRect(730, 220, 91, 23))
        self.plotButton.setObjectName("plotButton")
        self.gridLayoutWidget = QtWidgets.QWidget(plotGui)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(400, 10, 421, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.b2Current = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.b2Current.setObjectName("b2Current")
        self.gridLayout.addWidget(self.b2Current, 1, 1, 1, 1)
        self.SoC2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.SoC2.setObjectName("SoC2")
        self.gridLayout.addWidget(self.SoC2, 0, 1, 1, 1)
        self.b1Current = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.b1Current.setObjectName("b1Current")
        self.gridLayout.addWidget(self.b1Current, 1, 0, 1, 1)
        self.supplyCurrent = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.supplyCurrent.setObjectName("supplyCurrent")
        self.gridLayout.addWidget(self.supplyCurrent, 5, 1, 1, 1)
        self.loadCurrent = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.loadCurrent.setObjectName("loadCurrent")
        self.gridLayout.addWidget(self.loadCurrent, 6, 1, 1, 1)
        self.b2Cap = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.b2Cap.setObjectName("b2Cap")
        self.gridLayout.addWidget(self.b2Cap, 3, 1, 1, 1)
        self.b3Current = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.b3Current.setObjectName("b3Current")
        self.gridLayout.addWidget(self.b3Current, 1, 2, 1, 1)
        self.SoC3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.SoC3.setObjectName("SoC3")
        self.gridLayout.addWidget(self.SoC3, 0, 2, 1, 1)
        self.supplyVoltage = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.supplyVoltage.setObjectName("supplyVoltage")
        self.gridLayout.addWidget(self.supplyVoltage, 5, 0, 1, 1)
        self.b2Soc = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.b2Soc.setObjectName("b2Soc")
        self.gridLayout.addWidget(self.b2Soc, 4, 1, 1, 1)
        self.b3soc = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.b3soc.setObjectName("b3soc")
        self.gridLayout.addWidget(self.b3soc, 4, 2, 1, 1)
        self.b3Cap = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.b3Cap.setObjectName("b3Cap")
        self.gridLayout.addWidget(self.b3Cap, 3, 2, 1, 1)
        self.SoC1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.SoC1.setObjectName("SoC1")
        self.gridLayout.addWidget(self.SoC1, 0, 0, 1, 1)
        self.b1Cap = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.b1Cap.setObjectName("b1Cap")
        self.gridLayout.addWidget(self.b1Cap, 3, 0, 1, 1)
        self.loadVoltage = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.loadVoltage.setObjectName("loadVoltage")
        self.gridLayout.addWidget(self.loadVoltage, 6, 0, 1, 1)
        self.b1soc = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.b1soc.setObjectName("b1soc")
        self.gridLayout.addWidget(self.b1soc, 4, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 2, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 2, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 2, 2, 1, 1)
        self.plotStatus = QtWidgets.QLabel(plotGui)
        self.plotStatus.setGeometry(QtCore.QRect(400, 220, 321, 21))
        self.plotStatus.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.plotStatus.setObjectName("plotStatus")
        self.peuLbl1.setBuddy(self.inputPeu1)
        self.effLbl1.setBuddy(self.inputEff1)
        self.capLbl1.setBuddy(self.inputCap1)
        self.capLbl2.setBuddy(self.inputCap2)
        self.effLbl2.setBuddy(self.inputEff2)
        self.peuLbl2.setBuddy(self.inputPeu2)
        self.capLbl3.setBuddy(self.inputCap3)
        self.effLbl3.setBuddy(self.inputEff3)
        self.peuLbl3.setBuddy(self.inputPeu3)
        self.plotStatus.setBuddy(self.plotButton)

        self.retranslateUi(plotGui)
        self.slideEff1.sliderMoved['int'].connect(self.inputEff1.setValue)
        self.slidePeu2.sliderMoved['int'].connect(self.inputPeu2.setValue)
        self.slideEff2.sliderMoved['int'].connect(self.inputEff2.setValue)
        self.slidePeu3.sliderMoved['int'].connect(self.inputPeu3.setValue)
        self.slideEff3.sliderMoved['int'].connect(self.inputEff3.setValue)
        self.inputEff1.valueChanged['int'].connect(self.slideEff1.setValue)
        self.inputPeu2.valueChanged['int'].connect(self.slidePeu2.setValue)
        self.inputEff2.valueChanged['int'].connect(self.slideEff2.setValue)
        self.inputPeu3.valueChanged['int'].connect(self.slidePeu3.setValue)
        self.inputEff3.valueChanged['int'].connect(self.slideEff3.setValue)
        self.inputPeu1.valueChanged['int'].connect(self.slidePeu1.setValue)
        self.slidePeu1.sliderMoved['int'].connect(self.inputPeu1.setValue)
        QtCore.QMetaObject.connectSlotsByName(plotGui)
        plotGui.setTabOrder(self.currentDir, self.listDir)
        plotGui.setTabOrder(self.listDir, self.browseBtn)
        plotGui.setTabOrder(self.browseBtn, self.SoC1)
        plotGui.setTabOrder(self.SoC1, self.SoC2)
        plotGui.setTabOrder(self.SoC2, self.SoC3)
        plotGui.setTabOrder(self.SoC3, self.b1Current)
        plotGui.setTabOrder(self.b1Current, self.b2Current)
        plotGui.setTabOrder(self.b2Current, self.b3Current)
        plotGui.setTabOrder(self.b3Current, self.checkBox)
        plotGui.setTabOrder(self.checkBox, self.checkBox_2)
        plotGui.setTabOrder(self.checkBox_2, self.checkBox_3)
        plotGui.setTabOrder(self.checkBox_3, self.b1Cap)
        plotGui.setTabOrder(self.b1Cap, self.b2Cap)
        plotGui.setTabOrder(self.b2Cap, self.b3Cap)
        plotGui.setTabOrder(self.b3Cap, self.b1soc)
        plotGui.setTabOrder(self.b1soc, self.b2Soc)
        plotGui.setTabOrder(self.b2Soc, self.b3soc)
        plotGui.setTabOrder(self.b3soc, self.supplyVoltage)
        plotGui.setTabOrder(self.supplyVoltage, self.supplyCurrent)
        plotGui.setTabOrder(self.supplyCurrent, self.loadVoltage)
        plotGui.setTabOrder(self.loadVoltage, self.loadCurrent)
        plotGui.setTabOrder(self.loadCurrent, self.plotButton)
        plotGui.setTabOrder(self.plotButton, self.inputPeu1)
        plotGui.setTabOrder(self.inputPeu1, self.slidePeu1)
        plotGui.setTabOrder(self.slidePeu1, self.inputEff1)
        plotGui.setTabOrder(self.inputEff1, self.slideEff1)
        plotGui.setTabOrder(self.slideEff1, self.inputCap1)
        plotGui.setTabOrder(self.inputCap1, self.inputPeu2)
        plotGui.setTabOrder(self.inputPeu2, self.slidePeu2)
        plotGui.setTabOrder(self.slidePeu2, self.inputEff2)
        plotGui.setTabOrder(self.inputEff2, self.slideEff2)
        plotGui.setTabOrder(self.slideEff2, self.inputCap2)
        plotGui.setTabOrder(self.inputCap2, self.inputPeu3)
        plotGui.setTabOrder(self.inputPeu3, self.slidePeu3)
        plotGui.setTabOrder(self.slidePeu3, self.inputEff3)
        plotGui.setTabOrder(self.inputEff3, self.slideEff3)
        plotGui.setTabOrder(self.slideEff3, self.inputCap3)

    def retranslateUi(self, plotGui):
        _translate = QtCore.QCoreApplication.translate
        plotGui.setWindowTitle(_translate("plotGui", "My First Gui!"))
        self.fileProp.setTitle(_translate("plotGui", "File properties"))
        self.currentDir.setText(_translate("plotGui", "No dir selected"))
        self.browseBtn.setText(_translate("plotGui", "Browse"))
        self.loadStatus.setText(_translate("plotGui", "No file loaded"))
        self.battery1.setTitle(_translate("plotGui", "Battery 1"))
        self.peuLbl1.setText(_translate("plotGui", "Peukert\'s * 10"))
        self.inputEff1.setSuffix(_translate("plotGui", "%"))
        self.effLbl1.setText(_translate("plotGui", "Efficiency"))
        self.capLbl1.setText(_translate("plotGui", "Capacity (Ah)"))
        self.battery2.setTitle(_translate("plotGui", "Battery 2"))
        self.capLbl2.setText(_translate("plotGui", "Capacity (Ah)"))
        self.inputEff2.setSuffix(_translate("plotGui", "%", "%"))
        self.effLbl2.setText(_translate("plotGui", "Efficiency"))
        self.peuLbl2.setText(_translate("plotGui", "Peukert\'s * 10"))
        self.battery3.setTitle(_translate("plotGui", "Battery 3"))
        self.capLbl3.setText(_translate("plotGui", "Capacity (Ah)"))
        self.inputEff3.setSuffix(_translate("plotGui", "%"))
        self.effLbl3.setText(_translate("plotGui", "Efficiency"))
        self.peuLbl3.setText(_translate("plotGui", "Peukert\'s * 10"))
        self.plotButton.setText(_translate("plotGui", "Update Plot"))
        self.b2Current.setText(_translate("plotGui", "B2 Current"))
        self.SoC2.setText(_translate("plotGui", "SoC 2"))
        self.b1Current.setText(_translate("plotGui", "B1 Current"))
        self.supplyCurrent.setText(_translate("plotGui", "Supply Current"))
        self.loadCurrent.setText(_translate("plotGui", "Load Current"))
        self.b2Cap.setText(_translate("plotGui", "B2 remain cap"))
        self.b3Current.setText(_translate("plotGui", "B3 Current"))
        self.SoC3.setText(_translate("plotGui", "SoC 3"))
        self.supplyVoltage.setText(_translate("plotGui", "Supply Voltage"))
        self.b2Soc.setText(_translate("plotGui", "B2 SoC"))
        self.b3soc.setText(_translate("plotGui", "B3 SoC"))
        self.b3Cap.setText(_translate("plotGui", "B3 remain cap"))
        self.SoC1.setText(_translate("plotGui", "SoC 1"))
        self.b1Cap.setText(_translate("plotGui", "B1 remain Cap"))
        self.loadVoltage.setText(_translate("plotGui", "Load Voltage"))
        self.b1soc.setText(_translate("plotGui", "B1 SoC"))
        self.checkBox.setText(_translate("plotGui", "B1 Voltage"))
        self.checkBox_2.setText(_translate("plotGui", "B2 Voltage"))
        self.checkBox_3.setText(_translate("plotGui", "B3 Voltage"))
        self.plotStatus.setText(_translate("plotGui", "Not plotted yet"))

